[package]
name = "rust_logic"
version = "0.1.0"
edition = "2021"

[lib]
# 必须声明为 cdylib，这样才会生成 .so 文件
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1" # 用于和 Java/Kotlin 交互
log = "0.4"
android_logger = "0.13"
libc = "0.2"

[profile.release]
opt-level = "z"      # 针对体积进行极限优化 (类似于 -Oz)
lto = true           # 开启链接时优化 (Link Time Optimization)
codegen-units = 1    # 减少并行的代码生成单元并提高优化效果
panic = "abort"      # 发生 panic 时直接中止，减少二进制体积并移除异常处理逻辑
strip = true         # 自动剥离符号表 (类似于 strip 命令)
