import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8080/api/v1';
function App(){const [token,setToken]=useState(localStorage.token||'');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [code,setCode]=useState('');const [mode,setMode]=useState('login');const [config,setConfig]=useState('{}');const [version,setVersion]=useState(0);const [msg,setMsg]=useState('');
const headers=()=>({'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})});
async function auth(path,body){const r=await fetch(API+path,{method:'POST',headers:headers(),body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);return j}
async function load(){const r=await fetch(API+'/config',{headers:{...headers(),...(version?{'If-None-Match':String(version)}:{})}});if(r.status===304)return;const j=await r.json();setConfig(JSON.stringify(j.config,null,2));setVersion(j.version)}
useEffect(()=>{if(token){load().catch(e=>setMsg(e.message));const t=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(t)}},[token]);
if(!token)return <main className="auth"><h1>紫孔雀云配置</h1><form onSubmit={async e=>{e.preventDefault();try{if(mode==='register'){await auth('/auth/register',{email,password});setMode('verify');setMsg('验证码已发送，请查收邮箱')}else{const j=await auth('/auth/login',{email,password});localStorage.token=j.token;setToken(j.token)}}catch(x){setMsg(x.message)}}}><input type="email" placeholder="邮箱" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="密码（至少 8 位）" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{mode==='register'?'注册':'登录'}</button></form>{mode!=='verify'&&<button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'创建账号':'返回登录'}</button>}{mode==='verify'&&<form onSubmit={async e=>{e.preventDefault();try{await auth('/auth/verify',{email,code});setMode('login');setMsg('验证成功，请登录')}catch(x){setMsg(x.message)}}}><input placeholder="邮箱验证码" value={code} onChange={e=>setCode(e.target.value)} required/><button>验证邮箱</button></form>}<p>{msg}</p></main>;
return <main><header><h1>配置中心</h1><button onClick={()=>{localStorage.removeItem('token');setToken('')}}>退出</button></header><section><div className="bar"><span>当前版本 v{version}</span><button onClick={async()=>{try{const parsed=JSON.parse(config);const r=await fetch(API+'/config',{method:'PUT',headers:headers(),body:JSON.stringify({config:parsed})});const j=await r.json();if(!r.ok)throw Error(j.error);setVersion(j.version);setMsg('配置已下发')}catch(e){setMsg('JSON 格式错误或发布失败: '+e.message)}}}>保存并下发</button></div><textarea value={config} onChange={e=>setConfig(e.target.value)} spellCheck="false"/><p>{msg}</p></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
